import Butter from "../../assets/butter.png";
import Strawberry from "../../assets/strawberry.png";


const products = [
    {
        id: 1,
        title: "Butter",
        price: 200.00,
        image: Butter,
    },
    {
        id: 2,
        title: "Strawberry",
        price: 200.00,
        image: Strawberry,
        category: "Fruits",
    },
    {
        id: 3,
        title: "Onion",
        price: 200.00,
        image: Onion,
        category: "Vegetables",
    },
    {
        id: 4,
        title: "Tomato",
        price: 200.00,
        image: Tomato,
        category: "Vegetables",
    },
    {
        id: 5,
        title: "Carrot",
        price: 200.00,
        image: Carrot,
        category: "Vegetables",
    },
    {
        id: 6,
        title: "Cucumber",
        price: 200.00,
        image: Cucumber,
        category: "Vegetables",
    },
    {
        id: 7,
        title: "Eggplant",
        price: 200.00,
        image: Eggplant,
        category: "Vegetables",
    },
    {
        id: 8,
        title: "Garlic",
        price: 200.00,
        image: Garlic,
        category: "Vegetables",
    },
    {
        id: 9,
        title: "Ginger",
        price: 200.00,
        image: Ginger,
        category: "Vegetables",
    },
    {
        id: 10,
        title: "Lettuce",
        price: 200.00,
        image: Lettuce,
        category: "Vegetables",
    },
    {
        id: 11,
        title: "Mushroom",
        price: 200.00,
        image: Mushroom,
        category: "Vegetables",
    },
    {
        id: 12,
        title: "Pepper",
        price: 200.00,
        image: Pepper,
        category: "Vegetables",
    },
    {
        id: 13,
        title: "Potato",
        price: 200.00,
        image: Potato,
        category: "Vegetables",
    },
    {
        id: 14,
        title: "Radish",
        price: 200.00,
        image: Radish,
        category: "Vegetables",
    },
    {
        id: 15,
        title: "Spinach",
        price: 200.00,
        image: Spinach,
        category: "Vegetables",
    },
    {
        id: 16,
        title: "Sweet Potato",
        price: 200.00,
        image: SweetPotato,
        category: "Vegetables",
    },
    {
        id: 17,
        title: "Turnip",
        price: 200.00,
        image: Turnip,
        category: "Vegetables",
    },
]